sudo: false
language: python

env:
  - PYTHON=2.7 PANDAS=0.19.2
  - PYTHON=3.4 PANDAS=0.18.1
  - PYTHON=3.5 PANDAS=0.19.2 COVERAGE='true'
  - PYTHON=3.6 PANDAS='master' LINT='true'

before_install:
  - echo "before_install"
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - pwd
  - uname -a
  - git --version
  - git tag

install:
  - ci/install_travis.sh

script:
  - source activate test-environment
  - pytest -s -v --cov=pandas_msgpack --cov-report xml:/tmp/pytest-cov.xml pandas_msgpack
  - if [ $COVERAGE ]; then codecov ; fi
  - if [ $LINT ]; then flake8 pandas_msgpack -v ; fi
